//! r-next — Sub-pel ME refinement (half-pel + quarter-pel) tests.
//!
//! Round 49 (`b5dbbbf`) shipped integer-pel ±16 SAD ME for the P-frame
//! encoder. This round adds two extra refinement stages:
//!
//! 1. Half-pel 8-neighbour around the integer-pel winner, using the
//!    §6.3 `sub_pel_filters_8` / §8.5.4.2 EightTap luma filter to
//!    interpolate the reference block at each candidate.
//! 2. Quarter-pel 8-neighbour around the half-pel winner.
//!
//! Fixtures are generated by applying the SAME EightTap filter to a
//! source pattern at the target sub-pel phase — so the optimal MV is
//! exactly the half-pel or quarter-pel shift, and the encoder MC must
//! reproduce the filtered output bit-for-bit (modulo any §8.8 loop
//! filter touch-up at SB boundaries).
//!
//! Coverage:
//!   * `pframe_half_pel_translation_high_psnr` — 0.5 px horizontal
//!     shift, ≥ 38 dB PSNR_Y.
//!   * `pframe_quarter_pel_translation_high_psnr` — 0.25 px shift,
//!     ≥ 36 dB PSNR_Y.
//!   * `pframe_integer_pel_translation_no_regression` — 4 px shift
//!     (the r49 fixture); sub-pel can only help, so PSNR_Y must STILL
//!     be ≥ 49 dB.

use oxideav_core::{CodecId, CodecParameters, Frame, Packet, TimeBase};
use oxideav_vp9::{
    encoder::{encode_keyframe_yuv, encode_pframe_yuv, EncoderParams, ReferenceFrame, YuvFrame},
    make_decoder, CODEC_ID_STR,
};

const W: u32 = 64;
const H: u32 = 64;

/// PSNR in dB between two equal-length 8-bit planes.
fn psnr_db(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len());
    let mut sse: u64 = 0;
    for (x, y) in a.iter().zip(b.iter()) {
        let d = *x as i32 - *y as i32;
        sse += (d * d) as u64;
    }
    if sse == 0 {
        return f64::INFINITY;
    }
    let mse = (sse as f64) / (a.len() as f64);
    10.0 * (255.0 * 255.0 / mse).log10()
}

/// VP9 §6.3 `sub_pel_filters_8` EIGHTTAP filter — phase 8 = 1/2 sample,
/// phase 4 = 1/4 sample. Copied here so we don't reach into the
/// crate-private `mcfilter` module; the test only needs the two phases
/// we generate fixtures at.
const FILTER_EIGHTTAP_PHASE_8: [i32; 8] = [-1, 6, -19, 78, 78, -19, 6, -1];
const FILTER_EIGHTTAP_PHASE_4: [i32; 8] = [-1, 4, -16, 112, 37, -11, 4, -1];
const FILTER_BITS: i32 = 7;

/// Apply an 8-tap horizontal filter with edge-clamp to produce a sub-pel
/// shifted source. `phase_taps` is one row of the 16-phase bank;
/// `int_offset` is the integer part of the column shift (negative ⇒
/// shift right by replicating left edge).
fn horiz_filter_8tap(
    src: &[u8],
    width: usize,
    height: usize,
    taps: &[i32; 8],
    int_offset: i32,
) -> Vec<u8> {
    let mut out = vec![0u8; width * height];
    for r in 0..height {
        for c in 0..width {
            // The filter is centred at tap index 3.
            let base_c = c as i32 + int_offset;
            let mut acc = 0i32;
            for (k, &t) in taps.iter().enumerate() {
                let sc = (base_c + k as i32 - 3).clamp(0, width as i32 - 1) as usize;
                acc += (src[r * width + sc] as i32) * t;
            }
            let v = (acc + (1 << (FILTER_BITS - 1))) >> FILTER_BITS;
            out[r * width + c] = v.clamp(0, 255) as u8;
        }
    }
    out
}

/// Build a 64×64 4:2:0 frame from a luma function. Chroma stays at 128.
fn make_yuv<F: FnMut(usize, usize) -> u8>(mut f: F) -> (Vec<u8>, Vec<u8>, Vec<u8>) {
    let mut y = vec![0u8; (W * H) as usize];
    for r in 0..H as usize {
        for c in 0..W as usize {
            y[r * W as usize + c] = f(r, c);
        }
    }
    let uv_size = ((W / 2) * (H / 2)) as usize;
    (y, vec![128u8; uv_size], vec![128u8; uv_size])
}

/// Encode frame 1 (key), decode for the reconstructed reference.
fn encode_key_and_decode_recon(p: &EncoderParams, src: &YuvFrame<'_>) -> (Vec<u8>, ReferenceFrame) {
    let key_bytes = encode_keyframe_yuv(p, src);
    let params = CodecParameters::video(CodecId::new(CODEC_ID_STR));
    let mut dec = make_decoder(&params).expect("make_decoder");
    let pkt = Packet::new(0, TimeBase::new(1, 30), key_bytes.clone());
    dec.send_packet(&pkt).expect("send key");
    let f = dec.receive_frame().expect("recv key");
    let Frame::Video(v) = f else {
        panic!("expected Video");
    };
    let y = v.planes[0].data.clone();
    let y_stride = v.planes[0].stride;
    let u = v.planes[1].data.clone();
    let uv_stride = v.planes[1].stride;
    let vv = v.planes[2].data.clone();
    let refr = ReferenceFrame {
        y,
        y_stride,
        u,
        v: vv,
        uv_stride,
        width: W,
        height: H,
    };
    (key_bytes, refr)
}

/// Decode a key + P pair, return the decoded P-frame luma at W×H.
fn decode_pframe_luma(key_bytes: &[u8], p_bytes: &[u8]) -> Vec<u8> {
    let params = CodecParameters::video(CodecId::new(CODEC_ID_STR));
    let mut dec = make_decoder(&params).expect("make_decoder");
    dec.send_packet(&Packet::new(0, TimeBase::new(1, 30), key_bytes.to_vec()))
        .expect("send key");
    let _ = dec.receive_frame().expect("recv key");
    dec.send_packet(&Packet::new(1, TimeBase::new(1, 30), p_bytes.to_vec()))
        .expect("send pframe");
    let f2 = dec.receive_frame().expect("recv pframe");
    let Frame::Video(v) = f2 else {
        panic!("expected Video");
    };
    let stride = v.planes[0].stride;
    let mut y = Vec::with_capacity((W * H) as usize);
    for r in 0..H as usize {
        y.extend_from_slice(&v.planes[0].data[r * stride..r * stride + W as usize]);
    }
    y
}

/// Half-pel horizontal translation: frame 2 = EightTap-half-pel-shifted
/// version of (the decoded reconstruction of) frame 1. The encoder
/// should pick MV ≈ (0, 4) in 1/8-pel units = 0.5 px right.
#[test]
fn pframe_half_pel_translation_high_psnr() {
    let p = EncoderParams::keyframe(W, H);
    // Frame 1: smooth ramp so the filter response is well-defined.
    let (y1, u1, v1) = make_yuv(|_r, c| 40 + (c as u8) * 3);
    let src1 = YuvFrame {
        y: &y1,
        y_stride: W as usize,
        u: &u1,
        v: &v1,
        uv_stride: (W / 2) as usize,
        width: W,
        height: H,
    };
    let (key_bytes, refr) = encode_key_and_decode_recon(&p, &src1);

    // Frame 2 is the EightTap half-pel-shifted (phase 8) version of the
    // reconstructed frame 1. Using the reconstruction (not the source)
    // means the encoder's MC against the reference reproduces frame 2
    // exactly when MV = half-pel.
    let mut refl = vec![0u8; (W * H) as usize];
    for r in 0..H as usize {
        for c in 0..W as usize {
            refl[r * W as usize + c] = refr.y[r * refr.y_stride + c];
        }
    }
    let y2 = horiz_filter_8tap(&refl, W as usize, H as usize, &FILTER_EIGHTTAP_PHASE_8, 0);
    let uv_size = ((W / 2) * (H / 2)) as usize;
    let u2 = vec![128u8; uv_size];
    let v2 = vec![128u8; uv_size];
    let src2 = YuvFrame {
        y: &y2,
        y_stride: W as usize,
        u: &u2,
        v: &v2,
        uv_stride: (W / 2) as usize,
        width: W,
        height: H,
    };
    let p_bytes = encode_pframe_yuv(&p, &src2, &refr);
    let decoded_y = decode_pframe_luma(&key_bytes, &p_bytes);
    let psnr = psnr_db(&y2, &decoded_y);
    eprintln!(
        "half-pel: I-frame={} B, P-frame={} B, PSNR_Y = {psnr:.2} dB",
        key_bytes.len(),
        p_bytes.len()
    );
    assert!(psnr >= 38.0, "half-pel PSNR_Y {psnr:.2} dB < 38 dB");
}

/// Quarter-pel horizontal translation: frame 2 = EightTap-phase-4 shift
/// of the reconstructed frame 1. Encoder should pick MV ≈ (0, 2) in
/// 1/8-pel units = 0.25 px right.
#[test]
fn pframe_quarter_pel_translation_high_psnr() {
    let p = EncoderParams::keyframe(W, H);
    let (y1, u1, v1) = make_yuv(|_r, c| 50 + (c as u8) * 2);
    let src1 = YuvFrame {
        y: &y1,
        y_stride: W as usize,
        u: &u1,
        v: &v1,
        uv_stride: (W / 2) as usize,
        width: W,
        height: H,
    };
    let (key_bytes, refr) = encode_key_and_decode_recon(&p, &src1);

    let mut refl = vec![0u8; (W * H) as usize];
    for r in 0..H as usize {
        for c in 0..W as usize {
            refl[r * W as usize + c] = refr.y[r * refr.y_stride + c];
        }
    }
    let y2 = horiz_filter_8tap(&refl, W as usize, H as usize, &FILTER_EIGHTTAP_PHASE_4, 0);
    let uv_size = ((W / 2) * (H / 2)) as usize;
    let u2 = vec![128u8; uv_size];
    let v2 = vec![128u8; uv_size];
    let src2 = YuvFrame {
        y: &y2,
        y_stride: W as usize,
        u: &u2,
        v: &v2,
        uv_stride: (W / 2) as usize,
        width: W,
        height: H,
    };
    let p_bytes = encode_pframe_yuv(&p, &src2, &refr);
    let decoded_y = decode_pframe_luma(&key_bytes, &p_bytes);
    let psnr = psnr_db(&y2, &decoded_y);
    eprintln!(
        "quarter-pel: I-frame={} B, P-frame={} B, PSNR_Y = {psnr:.2} dB",
        key_bytes.len(),
        p_bytes.len()
    );
    assert!(psnr >= 36.0, "quarter-pel PSNR_Y {psnr:.2} dB < 36 dB");
}

/// Regression: the r49 integer-pel 4-px translation fixture. Sub-pel
/// refinement can only help, never hurt — the integer-pel candidate is
/// in the search set as the starting point, so any improvement is a
/// strict-lower SAD and any "no improvement" leaves the integer MV
/// intact. Expect the same PSNR_Y as r49 (≥ 49 dB).
#[test]
fn pframe_integer_pel_translation_no_regression() {
    let p = EncoderParams::keyframe(W, H);
    let (y1, u1, v1) = make_yuv(|_r, c| 60 + (c as u8) * 3);
    let src1 = YuvFrame {
        y: &y1,
        y_stride: W as usize,
        u: &u1,
        v: &v1,
        uv_stride: (W / 2) as usize,
        width: W,
        height: H,
    };
    let (key_bytes, refr) = encode_key_and_decode_recon(&p, &src1);
    let (y2, u2, v2) = make_yuv(|r, c| {
        let src_c = c.saturating_sub(4);
        y1[r * W as usize + src_c]
    });
    let src2 = YuvFrame {
        y: &y2,
        y_stride: W as usize,
        u: &u2,
        v: &v2,
        uv_stride: (W / 2) as usize,
        width: W,
        height: H,
    };
    let p_bytes = encode_pframe_yuv(&p, &src2, &refr);
    let decoded_y = decode_pframe_luma(&key_bytes, &p_bytes);
    let psnr = psnr_db(&y2, &decoded_y);
    eprintln!(
        "integer-pel 4 px: I-frame={} B, P-frame={} B, PSNR_Y = {psnr:.2} dB",
        key_bytes.len(),
        p_bytes.len()
    );
    assert!(
        psnr >= 49.0,
        "integer-pel regression: PSNR_Y {psnr:.2} dB < 49 dB (r49 baseline 49.96)"
    );
}
